In [73]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

In [74]:
data = pd.read_csv(r"C:\Users\giao\Desktop\作业\抽样技术\十抽五算法\diamonds.csv")

In [75]:
data.head()

price  carat      cut color clarity     x     y     z
0    326   0.23    Ideal     E     SI2  3.95  3.98  2.43
1    326   0.21  Premium     E     SI1  3.89  3.84  2.31
2    327   0.23     Good     E     VS1  4.05  4.07  2.31
3    334   0.29  Premium     I     VS2  4.20  4.23  2.63
4    335   0.31     Good     J     SI2  4.34  4.35  2.75

In [76]:
data.describe()

price         carat             x             y             z
count  53940.000000  53940.000000  53940.000000  53940.000000  53940.000000
mean    3932.799722      0.797940      5.731157      5.734526      3.538734
std     3989.439738      0.474011      1.121761      1.142135      0.705699
min      326.000000      0.200000      0.000000      0.000000      0.000000
25%      950.000000      0.400000      4.710000      4.720000      2.910000
50%     2401.000000      0.700000      5.700000      5.710000      3.530000
75%     5324.250000      1.040000      6.540000      6.540000      4.040000
max    18823.000000      5.010000     10.740000     58.900000     31.800000

In [80]:
data0 = data.sample(5000,replace = False)[['carat','price']].values
data0
data1  = []
for i in range(500):
    data2 = data0
    data1.append(data0)
print(data1)

[array([[1.5100e+00, 1.2872e+04],
       [7.0000e-01, 2.5700e+03],
       [7.1000e-01, 3.8010e+03],
       ...,
       [4.3000e-01, 1.3040e+03],
       [9.0000e-01, 3.1600e+03],
       [4.0000e-01, 8.5000e+02]]), array([[1.5100e+00, 1.2872e+04],
       [7.0000e-01, 2.5700e+03],
       [7.1000e-01, 3.8010e+03],
       ...,
       [4.3000e-01, 1.3040e+03],
       [9.0000e-01, 3.1600e+03],
       [4.0000e-01, 8.5000e+02]]), array([[1.5100e+00, 1.2872e+04],
       [7.0000e-01, 2.5700e+03],
       [7.1000e-01, 3.8010e+03],
       ...,
       [4.3000e-01, 1.3040e+03],
       [9.0000e-01, 3.1600e+03],
       [4.0000e-01, 8.5000e+02]]), array([[1.5100e+00, 1.2872e+04],
       [7.0000e-01, 2.5700e+03],
       [7.1000e-01, 3.8010e+03],
       ...,
       [4.3000e-01, 1.3040e+03],
       [9.0000e-01, 3.1600e+03],
       [4.0000e-01, 8.5000e+02]]), array([[1.5100e+00, 1.2872e+04],
       [7.0000e-01, 2.5700e+03],
       [7.1000e-01, 3.8010e+03],
       ...,
       [4.3000e-01, 1.3040e+03],
       

In [56]:
x = data0[:,0].reshape(-1,1)
x

array([[1.  ],
       [0.8 ],
       [1.5 ],
       ...,
       [1.12],
       [0.82],
       [0.7 ]])

In [58]:
y = data0[:,1].reshape(-1,1)
y

array([[4766.],
       [1350.],
       [6306.],
       ...,
       [4641.],
       [3588.],
       [2498.]])

In [59]:
reg = LinearRegression()

In [60]:
reg.fit(x,y)

LinearRegression()

In [62]:
print("The linear model is: Y = {:.5} + {:.5}X".format(reg.intercept_[0], reg.coef_[0][0]))

The linear model is: Y = -2210.6 + 7701.3X


In [64]:
β = reg.coef_[0]
β

array([7701.28063968])

In [66]:
data0 = range(2)
print(data0)


range(0, 2)


In [67]:
range(2)

range(0, 2)

In [68]:
np.arange(2)

array([0, 1])

[range(0, 2), range(0, 2), range(0, 2), range(0, 2), range(0, 2), range(0, 2), range(0, 2), range(0, 2), range(0, 2), range(0, 2), range(0, 2), range(0, 2), range(0, 2), range(0, 2), range(0, 2), range(0, 2), range(0, 2), range(0, 2), range(0, 2), range(0, 2), range(0, 2), range(0, 2), range(0, 2), range(0, 2), range(0, 2), range(0, 2), range(0, 2), range(0, 2), range(0, 2), range(0, 2), range(0, 2), range(0, 2), range(0, 2), range(0, 2), range(0, 2), range(0, 2), range(0, 2), range(0, 2), range(0, 2), range(0, 2), range(0, 2), range(0, 2), range(0, 2), range(0, 2), range(0, 2), range(0, 2), range(0, 2), range(0, 2), range(0, 2), range(0, 2), range(0, 2), range(0, 2), range(0, 2), range(0, 2), range(0, 2), range(0, 2), range(0, 2), range(0, 2), range(0, 2), range(0, 2), range(0, 2), range(0, 2), range(0, 2), range(0, 2), range(0, 2), range(0, 2), range(0, 2), range(0, 2), range(0, 2), range(0, 2), range(0, 2), range(0, 2), range(0, 2), range(0, 2), range(0, 2), range(0, 2), range(0, 2)